# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170817_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cat_id',
        ),
        migrations.AlterField(
            model_name='article',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='Category'),
        ),
    ]
