# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 06:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20170825_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='art',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.article'),
        ),
    ]
