# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20170828_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Image'),
        ),
    ]
